### PR TITLE
Allow iterables to be passed in for merging

### PR DESCRIPTION
**Pull request by svisser**
This is a pull request for #1 by making use of the abstract base classes in the collections module. For dictionaries and other mapping objects, use `update()` and for iterable objects, iterate and `update()`.

### CODE REVIEW

**Comment by nvie** [comment]
Thanks!

**Comment by svisser** [comment]
Thanks for merging!

**Comment by nvie** [comment]
Released 0.2.0 with this patch included.

**Comment by svisser** [comment]
Thanks again for releasing it so quickly, updating my code now :+1:

**Pull request merged**
